FROM node:22-bullseye

RUN apt-get update && apt-get install -y openjdk-11-jre

RUN npm install -g @openapitools/openapi-generator-cli

RUN npm install -g nodemon 

RUN npm install -g pnpm

COPY scripts /scripts

RUN chmod +x /scripts/generate-api-client.sh

WORKDIR /scripts

ENTRYPOINT ["nodemon", "--watch", "/local/apps/api/openapi.json", "--exec", "sh", "./generate-api-client.sh"]